# -*- coding: utf-8 -*-
"""[1330번] 두 수 비교하기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18Mpe8iQafslvebBn-NdDg4RRPWOcyn4U
"""

A, B = map(int,input().split())

if A>B:
  print('>')
elif A<B:
  print('<')
else:
  print('==')