# -*- coding: utf-8 -*-
"""[1012번] 유기농 배추.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JZRWYmNIJB8cmg6aXNM__4de0nIVL1aE
"""

import sys
r=sys.stdin.readline
T=int(r())
dx = [1,-1,0,0]
dy = [0,0,1,-1]
for _ in range(T):
	M,N,K = map(int,r().split())
	field =[[0] * M for _ in range(N)]
	q = []
	worm = 0
	for _ in range(K):
		X,Y = map(int,r().split())
		field[Y][X] = 1
	for y in range(N):
		for x in range(M):
			if field[y][x]:
				q.append((x,y))
				worm += 1
				while q:
					temp = q[0]
					q = q[1:]
					if field[temp[1]][temp[0]]:
						field[temp[1]][temp[0]] = 0
						for i in range(4):
							new_x = temp[0] + dx[i]
							new_y = temp[1] + dy[i]
							if 0 <= new_x < M and 0 <= new_y < N and field[new_y][new_x]:
								q.append((new_x,new_y))
	print(worm)