# -*- coding: utf-8 -*-
"""[1021 번] 회전하는 큐.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13IMo5sIYm9T9azITqWltXt2ztUNVYAFD
"""

import sys
r = sys.stdin.readline
N,M = map(int,r().split())
l = list(map(int,r().split()))
deq = [i for i in range(1,N+1)]
c = 0
while len(l) > 0:
	if deq[0] == l[0]:
		l.pop(0)
		deq.pop(0)
	else:
		idx = deq.index(l[0])
		if idx <= len(deq) // 2:
			c += idx
			deq = deq[idx:] + deq[:idx]
			deq.pop(0)
			l.pop(0)
		else:
			c += len(deq) - idx
			deq = deq[(idx+1):] + deq[:(idx+1)]
			deq.pop()
			l.pop(0)
print(c)