# -*- coding: utf-8 -*-
"""[1874번] 스택 수열.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18Mpe8iQafslvebBn-NdDg4RRPWOcyn4U
"""

import sys
r = sys.stdin.readline
n = int(r())
c = 0
l = []
res = []
flag = 0
for _ in range(n):
	num = int(r())
	
	while c < num:
		c += 1
		l.append(c)
		res.append("+")
	
	if l[-1] == num:
		l.pop()
		res.append("-")
	else:
		flag = 1
		break

if flag == 1:
	print("NO")
else:
	print(*res, sep="\n")