# -*- coding: utf-8 -*-
"""[10773번] 제로.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OieqvIuSMcYc4hBz6HVLbQtEPfNEoaid
"""

import sys
r = sys.stdin.readline

k,*nums = int(r()),
for _ in range(k):
	n = int(r())
	if n != 0:
		nums.append(n)
	else:
		nums.pop()
print(sum(nums))