# -*- coding: utf-8 -*-
"""[10869번] 사칙연산.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A9fD7MDiY7uNLoThjRy123YnPTytxvNl
"""

A, B = map(int,input().split())
print(A+B)
print(A-B)
print(A*B)
print(A//B)
print(A%B)