# -*- coding: utf-8 -*-
"""[9012번] 괄호.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U8jzMtX92-SN77Bv5wNXq3iy6OmE_A1-
"""

import sys
r = sys.stdin.readline
T = int(r())
for _ in range(T):
	p = list(r().rstrip())
	c = []
	d = 0
	for i in p:
		if i == "(":
			c.append(1)
		elif i == ")":
			try:
				c.pop()
			except:
				print("NO")
				d = 1
			break
	if len(c) == 0 and d != 1:
		print("YES")
	else:
		print("NO")