# -*- coding: utf-8 -*-
"""[1001번] A-B.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oHuVTPX_D716gR8uanHjeh2nch-dYWAR
"""

A, B = input().split()
print(int(A)-int(B))