# -*- coding: utf-8 -*-
"""[18258번] 큐 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18Mpe8iQafslvebBn-NdDg4RRPWOcyn4U
"""

from collections import deque

def reverse_pop(l):
	return l.reverse().pop()

def push(X):
	deq.append(X)
	
def pop():
	if len(deq) == 0:
		return -1
	else:
		return deq.popleft()
		
def size():
	return len(deq)

def empty():
	if len(deq) == 0:
		return 1
	else:
		return 0

def front():
	if len(deq) == 0:
		return -1
	else:
		return deq[0]

def back():
	if len(deq) == 0:
		return -1
	else:
		return deq[-1]
		
import sys
r = sys.stdin.readline
N,*que = int(r()),
deq = deque(que)
for _ in range(N):
	w = r().rstrip()
	if w[:4] == "push":
		push(w[5:])
	elif w == "pop":
		print(pop())
	elif w == "size":
		print(size())
	elif w == "empty":
		print(empty())
	elif w == "front":
		print(front())
	elif w == "back":
		print(back())