# -*- coding: utf-8 -*-
"""[2557번] Hello World.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tKSZqPSEJzRONKew55x6RCrZphtJdau0
"""

print("Hello World!")