# -*- coding: utf-8 -*-
"""[10998번] A*B.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z-dYPno1yG7Hys-ucbGGoz5VEaateDat
"""

A, B = input().split()
print(int(A)*int(B))