# -*- coding: utf-8 -*-
"""[1966 번] 프린터 큐.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13IMo5sIYm9T9azITqWltXt2ztUNVYAFD
"""

from collections import deque
import sys
r = sys.stdin.readline
t = int(r())
for _ in range(t):
	N,M = map(int,r().split())
	p = list(map(int,r().split()))
	deq = deque(p)
	count = 0
	while max(deq) != deq[M]:
		if deq[0] == max(deq):
			deq.popleft()
			count += 1
			if M != 0:
				M -= 1
			else:
				M = len(deq) - 1
		else:
			deq.append(deq.popleft())
			if M != 0:
				M -= 1
			else:
				M = len(deq) - 1
	count2 = 0
	for i in range(M+1):
		if deq[i] == deq[M]:
			count2 += 1
	count = count + count2
	print(count)