# -*- coding: utf-8 -*-
"""[9498번] 시험 성적.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18Mpe8iQafslvebBn-NdDg4RRPWOcyn4U
"""

score = int(input())

if score >= 90: print("A")
elif score>=80: print("B")
elif score>=70: print("C")
elif score>=60: print("D")
else: print("F")