# -*- coding: utf-8 -*-
"""[1912번] 연속합.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JZRWYmNIJB8cmg6aXNM__4de0nIVL1aE
"""

import sys
r = sys.stdin.readline
N = int(r())
num = list(map(int,r().split()))
dp = [0] * N
dp[0] = num[0]
for i in range(1, len(num)):
	dp[i] = max(0, dp[i-1] + num[i])
	

ans = max(dp)
if ans==0:
	print(max(num))
else:
	print(ans)