# -*- coding: utf-8 -*-
"""[15651번] N과M(3).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JZRWYmNIJB8cmg6aXNM__4de0nIVL1aE
"""

import sys
r=sys.stdin.readline
N,M=map(int,r().split())
nums=[i+1 for i in range(N)]
res=[]

def dfs(cnt):
	if cnt==M:
		print(*res)
		return
	
	for i in range(N):
		res.append(nums[i])
		dfs(cnt+1)
		res.pop()

dfs(0)