# -*- coding: utf-8 -*-
"""[2588번] 곱셈.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eevX7Vuq3JIKJK5HLkIm47QRX60cjo6t
"""

A = int(input())
B = int(input())

output1 = A*((B%100)%10)
output2 = A*((B%100)//10)
output3 = A*(B//100)
output4 = A*B

print(output1, output2, output3, output4, sep="\n")