# -*- coding: utf-8 -*-
"""[10826번] 피보나치 수 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JZRWYmNIJB8cmg6aXNM__4de0nIVL1aE
"""

import sys
r=sys.stdin.readline
N=int(r())

def fibo_DP(n):
	a,b=0,1
	for i in range(n):
		a,b = b,a+b
	return a

print(fibo_DP(N))