# -*- coding: utf-8 -*-
"""[10172번] 개.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oHuVTPX_D716gR8uanHjeh2nch-dYWAR
"""

print("|\_/|")
print("|q p|   /}")
print('( 0 )"""\\')
print('|"^"`    |')
print("||_/=\\\__|")