# -*- coding: utf-8 -*-
"""[2164번] 카드2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MMQa62TSG5MzEddozqVAj2eHWAhZhs8o
"""

import sys
from collections import deque
r = sys.stdin.readline
N,*l = int(r()),
deq = deque(l)
for i in range(1,N+1):
	deq.append(i)
while len(deq) > 1:
	deq.popleft()
	deq.append(deq.popleft())
print(deq[0])