# -*- coding: utf-8 -*-
"""[1946번] 신입 사원.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JZRWYmNIJB8cmg6aXNM__4de0nIVL1aE
"""

import sys
r=sys.stdin.readline
T=int(r())
for _ in range(T):
	cnt=0
	N=int(r())
	l=[[0,0] for _ in range(N)]
	for i in range(N):
		a,b=map(int,r().split())
		l[i][0]=a
		l[i][1]=b
	l.sort(key=lambda x:(x[0]))
	cnt=1
	s=l[0][1]
	for i in range(1,N):
		if l[i][1] < s:
			s=l[i][1]
			cnt+=1
	print(cnt)