# -*- coding: utf-8 -*-
"""[2217번] 로프.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JZRWYmNIJB8cmg6aXNM__4de0nIVL1aE
"""

import sys
r=sys.stdin.readline
N,*l=int(r()),
for i in range(N): l.append(int(r()))

l = sorted(l, reverse=True)
res = []
for i in range(len(l)):
	res.append((i+1) * l[i])

print(max(res))