# -*- coding: utf-8 -*-
"""[1439번] 뒤집기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JZRWYmNIJB8cmg6aXNM__4de0nIVL1aE
"""

import sys
r=sys.stdin.readline
S = r().rstrip()
cnt = 0
for i in range(1, len(S)):
	if S[i-1] != S[i]:
		cnt += 1
print((cnt + 1) //2)