# -*- coding: utf-8 -*-
"""[11054번] 가장 긴 바이토닉 부분 수열.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JZRWYmNIJB8cmg6aXNM__4de0nIVL1aE
"""

import sys
r = sys.stdin.readline
N = int(r())
idp = [1] * N
ddp = [1] * N
l = list(map(int,r().split()))

# 증가하는 수열
for i in range(N):
	for j in range(i):
		if l[i] > l[j] and idp[i] < idp[j] + 1:
			idp[i] = idp[j] + 1

# 감소하는 수열
for i in range(N-1,-1,-1):
	for j in range(i+1,N):
		if l[i] > l[j] and ddp[i] < ddp[j] + 1:
			ddp[i] = ddp[j] + 1

result = []
for i,j in zip(idp,ddp):
	result.append(i+j)
print(max(result)-1)