# -*- coding: utf-8 -*-
"""[10171번] 고양이.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oHuVTPX_D716gR8uanHjeh2nch-dYWAR
"""

print("\    /\\")
print(" )  ( ')")
print("(  /  )")
print(" \(__)|")