# -*- coding: utf-8 -*-
"""[2178번] 미로 탐색.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JZRWYmNIJB8cmg6aXNM__4de0nIVL1aE
"""

import sys
r=sys.stdin.readline
N,M=map(int,r().split())
maze=[]
for _ in range(N):
	maze.append([int(i) for i in r().rstrip()])
dx=[1,-1,0,0]
dy=[0,0,1,-1]
q=[]
for y in range(N):
	for x in range(M):
		if maze[y][x]:
			q.append((x,y))
			while q:
				temp=q[0]
				q=q[1:]
				for i in range(4):
					new_x=temp[0]+dx[i]
					new_y=temp[1]+dy[i]
					if 0<=new_x<M and 0<=new_y<N and maze[new_y][new_x]==1:
						q.append((new_x,new_y))
						maze[new_y][new_x]=maze[temp[1]][temp[0]] + 1
print(maze[N-1][M-1])