# -*- coding: utf-8 -*-
"""[1008번] A/B.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A9fD7MDiY7uNLoThjRy123YnPTytxvNl
"""

A, B = input().split()
print(int(A)/int(B))