# -*- coding: utf-8 -*-
"""[15652번] N과M(4).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JZRWYmNIJB8cmg6aXNM__4de0nIVL1aE
"""

import sys
r=sys.stdin.readline
N,M=map(int,r().split())

nums=[i+1 for i in range(N)]
check=[False]*N
res=[]

def dfs(cnt):
	if cnt==M:
		print(*res)
		return
	
	for i in range(N):
		if check[i]:
			continue
		
		res.append(nums[i])
		dfs(cnt+1)
		res.pop()
		check[i]=True
		
		for j in range(i+1,N):
			check[j]=False

dfs(0)