# -*- coding: utf-8 -*-
"""[11047번] 동전 0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JZRWYmNIJB8cmg6aXNM__4de0nIVL1aE
"""

import sys
r=sys.stdin.readline
N,K=map(int,r().split())
l=[]
cnt=0
for _ in range(N): l.append(int(r()))

for i in l[::-1]:
	cnt += K // i
	K%=i
print(cnt)