# -*- coding: utf-8 -*-
"""[5568번] 카드 놓기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JZRWYmNIJB8cmg6aXNM__4de0nIVL1aE
"""

from itertools import permutations
import sys
r=sys.stdin.readline
n,k=int(r()),int(r())
nums=[]
for _ in range(n):
	nums.append(r().rstrip())

res=[]
for i in permutations(nums,k):
	res.append(''.join(i))
res=set(res)
print(len(res))