# -*- coding: utf-8 -*-
"""[10718번] We love krili.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tKSZqPSEJzRONKew55x6RCrZphtJdau0
"""

print("강한친구 대한육군\n강한친구 대한육군")