# -*- coding: utf-8 -*-
"""[11866번] 요세푸스 문제 0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MMQa62TSG5MzEddozqVAj2eHWAhZhs8o
"""

import sys
from collections import deque
r = sys.stdin.readline
N,K = map(int,r().split())
l = [i for i in range(1,N+1)]
res = []
deq = deque(l)
while len(deq) > 1:
	for _ in range(K-1):
		deq.append(deq.popleft())
	res.append(deq.popleft())
else:
	res.append(deq.popleft())

print('<%s>'%(', '.join(map(str,res))))